### ISSUE TITLE
Add Review? (Change to Add Justification..)

### ISSUE THREAD

**Issue by infamousmax** [PCMRating/pcmrating#12]
Add Review? is it a review or is it statistical information based on facts for justification? Maybe change the functionality of reviewing to Justification. Review makes it sound opinion based, this site seems to focus specifically on the facts?

Other titles for the functionality:

Add Information
Submit Information
Validate Requirements

**Comment by Lockyy** [comment]
We're sticking with just Review for now, we've got a tonne of technical information and the review doesn't factor into ratings at all. Users can put what they want in there, if it's objectionable or fallacious the review can be removed or the user banned.
