### ISSUE TITLE
Graphics and Statistical Analysis

### ISSUE THREAD

**Issue by infamousmax** [PCMRating/pcmrating#16]
I'm sure you are aware of what is needed and is possible.

Get some HTML5 on the go and make some pretty graphs, you get the data, now use it. Show people some trend analysis on recent activity, maybe do a trend on game release time and average change in factual stats etc.. would be neat-o.

**Comment by Lockyy** [comment]
We now have graphs on the landing page, you can view them with old site data at http://pcmrating-staging.herokuapp.com.
