### ISSUE TITLE
Templates markup

### ISSUE THREAD

**Issue by GBH** [PCMRating/pcmrating#24]
Why is it erb? Any objections to HAML?

**Comment by sergiotapia** [comment]
I would prefer Slim as it's faster to type and no more curly braces.

    # HAML
    .foo{bar: 'baz'}

    # Slim
    .foo bar='baz'

But yeah anything other than erb is better.

**Comment by Ruxton** [comment]
:+1: to HAML @Lockyy  .. what's yoru thoughts?

**Comment by tjhorner** [comment]
> no more curly braces

`{src: "foobar.jpg"}`

Right...

**Comment by tjhorner** [comment]
HAML is awesome, but would be kind of a pain to convert from ERB to HAML wouldn't it?

**Comment by sergiotapia** [comment]
Regardless now's the time to move to something better, not later when there's more stuff to rewrite.

**Comment by tjhorner** [comment]
Very true :+1:

**Comment by Lockyy** [comment]
I am 100% in favour of swapping over. I prefer the look of Slim so vote for that. If there is an overwhelming preference for HAML over it however we can go for that.

**Comment by Lockyy** [comment]
We're completely swapped over to SLIM now
