### ISSUE TITLE
Longer game listing

### ISSUE THREAD

**Issue by isaacrg** [PCMRating/pcmrating#29]
Please could the games listing page allow for more game entries, such that clicking tons of "next page" links isnt required. You could consider using pagination, but currently this is really irritating.

**Comment by sergiotapia** [comment]
Maybe 20 per page is a good compromise?

**Comment by isaacrg** [comment]
Perhaps. Also, ntroducing a "load more" button at the bottom, which would add the to the existing list would be useful, and perhaps better than massive pages.

**Comment by Lockyy** [comment]
Per page has been upped to 20 in the current latest version of the site up at http://pcmrating-staging.herokuapp.com
