### ISSUE TITLE
Add LICENSE file to repository.

### ISSUE THREAD

**Issue by sergiotapia** [PCMRating/pcmrating#37]
The codebase needs a license. I would recommend MIT because it has the least legalese out of all of the other ones, however it doesn't protect someone from cloning the code and launching a closed source alternative using everybody's work.

Up to @Lockyy what he feels is right, but now is the best time to do this because as more people contribute you're going to have to backtrack and get permissions from everybody to switch to the license terms. 

This has happened before on a very large project and it was a bitch to seek out and coordinate all the contributors.

**Comment by sebie** [comment]
I would agree with this. The sooner we get a LICENCE file the better for us all.

**Comment by JoshCode** [comment]
Also, if you wait too long with a license, it will be impossible to agree on one, since all the previous contributors will need to agree with the license used.
I also suggest using something like www.clahub.com, to avoid other legal issues.

**Comment by Lockyy** [comment]
I propose a Creative Commons license: [Attribution-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-sa/4.0/)

Opinions?

**Comment by sergiotapia** [comment]
Perfect! Use this for whatever you like, but you have to give appropriate credit and not restrict the license. :+1:

**Comment by JoshCode** [comment]
Creative Commons is a great license, however for software there are better licenses available. I have never seen an open source project use CC.
To scout for good licenses, I recommend looking at the pages of the [Open Source Initiative](http://opensource.org/) and their [licensing](http://opensource.org/licenses) page, or the [Free Software Foundation](http://www.fsf.org/) and their [licensing](http://www.fsf.org/licensing/) page.

**Comment by sergiotapia** [comment]
I'm not well versed with licenses.

@JoshCode I noticed that StackOverflow uses CC-ShareAlike because of all the user contributions (Q&A), how does this apply to PCMRating? Shouldn't we use the same license since we're also basically basing the entire site on user contributed content?

**Comment by JoshCode** [comment]
@sergiotapia I think that the CC-ShareAlike license applies to the user-produced content of the site, not the code of the site. I don't think that PCMRating needs a license for the content of the site, since (for now) no text reviews can be placed. Once they can be placed, the CC-ShareAlike license is a good license to use for the user-generated content. However, the code of the site, in my opinion, needs to be 'protected' by another license.

Note: I say 'protected' loosly, as open-source licenses exist to permit things, rather than prevent them, but I couldn't find another word for it.

**Comment by JoshCode** [comment]
Note 2: I was wrong, it is possible to place a review in user-written text, so yes, the content that users generate also need a license, which needs to be in the EULA.

**Comment by Lockyy** [comment]
Mhm, having read more the CC-ShareALike doesn't apply to software. I quite like the MIT license although as @sergiotapia mentioned, private use is non-ideal.

**Comment by Lockyy** [comment]
#44 Created an issue for the EULA @JoshCode

**Comment by JoshCode** [comment]
Private use is indeed always a problem with open-source projects. However, the spirit of open-source is that 1. everybody can contribute if they want to, and 2. that everybody can build upon your work.

You'll need to choose a license depending on what your ideology is.

As an example, my ideology for (almost) all the code I write is that anybody can use it, as long as they give me credit for my work. I'd be fine with businesses using my code, as that would spread my name and gives me free examples of people using my code, good for your CV.

The MIT License is one of the most permissive licenses that exist, so this wouldn't be ideal in my example, as forks of the project don't need to credit the original contributors.

The GNU GPL license is another popular license, this does require the users of your code to credit you and all other contributors to this project. This license also disallows anybody to use your code in a closed-source application in any way, which in my example would be bad.

If you need any help picking a license, I'd be willing to give you a hand, but keep in mind, I'm not a lawyer :stuck_out_tongue:

**Comment by Lockyy** [comment]
Having compared I think GPL would be best. @sergiotapia @tjhorner @fotvoren do you all agree? We four are the current contributors so if we all agree we can implement that and ensure all existing and future code related to this repo is licensed under the GPL.

**Comment by sergiotapia** [comment]
I'm cool with that. :+1:

**Comment by JoshCode** [comment]
Small end note: GPL does allow somebody to use your code in their open-source application and make money off of it. It does not prevent open-source commercial use, if you wanted to completely shut out commercial use.

**Comment by Ruxton** [comment]
I'd rather it was licensed MIT, like half the gems you're using? ;)  GPL is ok though I guess.

**Comment by tjhorner** [comment]
I'm fine with GPL.

**Comment by sebie** [comment]
I would go with MIT? But any licence the sooner we get it, the better.

**Comment by tjhorner** [comment]
Is WTFPL an option?

**Comment by sebie** [comment]
Untimatly I think that we should wait for @Lockyy to decide what his intentions with pcmrating is. 

He stated that "GPL would be the best". All we are doing now is waiting for @fotvoren to agree upon it, as he is part of the 4 toal contributers.

Other licences proposed:
* http://creativecommons.org/licenses/by-sa/4.0/
* MIT

-----

On a side note, I am suprised [choosealicence.com](http://choosealicence.com) has not been mentiond. And a mention to @JoshCode 's suggestion on [clahub.com](https://www.clahub.com).

:grey_question:

**Comment by fotvoren** [comment]
I'm fine with GPL, but wouldn't MIT be better?

**Comment by JoshCode** [comment]
I believe @Lockyy chose GPL to prevent closed-source private use.

Side note: GNU GPL doesn't prevent private usage as long as it isn't distributed.

Side note 2: If by private usage you meant commercial usage, GNU GPL doesn't prevent that either. (Strictly speaking, when preventing commercial usage, the code is no longer open-source by definition)

**Comment by Lockyy** [comment]
I've been going back and forth in my head over this decision for ages now and it feels like it's getting in the way of things. We're going with MIT and as soon as everyone says yes we'll get the license in the repo and be done with the discussion.

**Comment by JoshCode** [comment]
:+1: MIT is a great license.

Please also look into writing a [Contributor Licence Agreement](https://www.clahub.com/pages/why_cla), which will prevent contributors from causing legal trouble.

**Comment by sergiotapia** [comment]
I'm also ok with MIT.

**Comment by tjhorner** [comment]
Going back to @Ruxton's comment:

> I'd rather it was licensed MIT, like half the gems you're using?

So yeah, MIT is good.
