### ISSUE TITLE
Review edits not currently saving previous entries

### ISSUE THREAD

**Issue by Matakor** [PCMRating/pcmrating#4]
The only thing that remains the same currently is the typed reviews. Drop-down options all return to the lowest possible state. Should be a simple fix, but I felt it needed to be put up there so that people editing their reviews don't drop the rating without realizing it.

**Comment by Lockyy** [comment]
Thanks, will get this fixed as soon as I'm back at my computer.

**Comment by Lockyy** [comment]
Fixed in 39667cbd7203894ffee9f4577063a08d9cb51def
