### ISSUE TITLE
Add sitemap to website.

### ISSUE THREAD

**Issue by sergiotapia** [PCMRating/pcmrating#57]
A sitemap is a good way to have Google crawl us, I recommend using: dynamic_sitemaps. But I'm open to other options that may work better.

https://github.com/lassebunk/dynamic_sitemaps

Since we're hosted on Heroku, we can't really run the generator and voila (since Heroku wipes the drive regularly). We'll need to push the sitemap to something like S3 or whatever and link the generated sitemap there. What do you guys think?

For structure I'm thinking:

- Root
- Games
- Reviews

**Comment by tjhorner** [comment]
Is there any gem that dynamically generates a sitemap upon every visit?

**Comment by sergiotapia** [comment]
This gem does that. You just configure the models you want in your sitemap and it will automatically add them,

**Comment by tjhorner** [comment]
I thought you said that this was a generator...?

**Comment by Lockyy** [comment]
Implemented in #47
