### ISSUE TITLE
Search functionality?

### ISSUE THREAD

**Issue by peterkos** [PCMRating/pcmrating#6]
Would defiantly like to see search implemented, because manually browsing through only 6 games at a time gets very tiring.

**Comment by sergiotapia** [comment]
I can look into integrating Algolia search for the page if they allow us their community free plan. @Lockyy is pcmrating non-profit? Just want to confirm before asking them.

http://cl.ly/image/1X0U3H3w3j1W

**Comment by evsasse** [comment]
Would like to see some way search/view just the *Glorious*, or any other rank.

**Comment by Lockyy** [comment]
Basic search functionality is implemented in https://github.com/PCMRating/pcmrating/commit/9ddd8d3b3d06e755bb5d422bd87fd1900507e9ee
