### ISSUE TITLE
Glorious badge broken in current deploy

### ISSUE THREAD

**Issue by Ruxton** [PCMRating/pcmrating#62]
Looks like asset compilation died a bit in the last deploy and the currently displayed "Glorious" badge on the site is broken.

![](http://puu.sh/iLtpp/fad3a0c514.png)

**Comment by tjhorner** [comment]
Looks like there's an issue in the issue system... your screenshot looked like this in the email:

![](http://puu.sh/iLvBD/4a0351e26a.jpg)

**Comment by tjhorner** [comment]
Or did you edit it afterwards?

**Comment by Ruxton** [comment]
Yeah i put the wrong screenshot in and then edited it afterward. DERP.

How awesome does Voltron look though? :P

**Comment by tjhorner** [comment]
Looks like the Glorious badge is fixed:

![](http://www.pcmrating.com/assets/g-a98c2758b01df16fe859558a35eb384574b42c068b1a1136d574dda5add8adc5.jpg)

You can close this now.
