### ISSUE TITLE
Should "Maximum" be "Recommended"?

### ISSUE THREAD

**Issue by tjhorner** [PCMRating/pcmrating#70]
I say this because it isn't really the maximum, but it's the recommended for running at its normal performance. In [this file](https://github.com/PCMRating/pcmrating/blob/master/app/views/games/_game_show_top.slim#L57-L58) it gets the "recommended" value but says "maximum". Didn't create a PR yet, just wanted to discuss.

**Comment by Lockyy** [comment]
Fixed in 
https://github.com/PCMRating/pcmrating/commit/369e3a21ebbdd1278dc306328296f40fba921bfe

Thanks for the heads up
