### ISSUE TITLE
Social Integration

### ISSUE THREAD

**Issue by infamousmax** [PCMRating/pcmrating#9]
Allow people to register via popular social media outlets like Facebook, Google, Reddit.

Extended functionality could be added to allow liking of certain games, remember to do a special facebook like function so it shows friendly on their side.

This would also path the way for future side functionality ;)

**Comment by sebie** [comment]
I only have the following oAuth options: 
* GitHub
* Steam (duh)
* reddit

Only after these I would implement: Facebook, Twitter, Google (Plus) etc.

**Comment by Ruxton** [comment]
Starts with #3. (just mentioning so they link together) though this bug does continue on top of just "Login" with more integration.

**Comment by sebie** [comment]
Would you mind closing this as it is a dubplicate of #9? Thanks!

**Comment by tjhorner** [comment]
@sebie This _is_ #9... lol

**Comment by sebie** [comment]
Sorry I meant #3 ! My bad.. Edited.
